Implement audit fixes
catalystdao/GeneralisedIncentives pull request #40
Opened 2024-03-20 10:47 UTC by reednaa

This PR implements all of the audit fixes in 1 PR. This simplifies merging since each merge requires updating the respective gas arguments.

resolves #39, #38, #37, #36, #35, #34, #33, #32, #31

2024-03-20 16:10 UTC, jsanmigimeno requested changes
Aside from the minor README comments, the revert error `NotEnoughGasExeuction` name must also be corrected.

Logicwise seems good.

2024-04-02 10:05 UTC, jsanmigimeno approved these changes

2024-04-02 10:08 UTC, jsanmigimeno requested changes
Revert error `NotEnoughGasExeuction` is misspelt.

2024-04-02 10:47 UTC, reednaa commented
> Revert error `NotEnoughGasExeuction` is misspelt.

Which line?

2024-04-02 10:55 UTC, jsanmigimeno approved these changes

2024-04-02 10:57 UTC, merged